### ISSUE TITLE
Power off on idle

### ISSUE THREAD

**Issue by r00tdownx** [QIDITECH/QIDISlicer#1]
Hi is it possible for option to turn off printer after 10-20 mins idle?  Its kind of annoying that only power button is on back to.

**Comment by QIDITECH** [comment]
The off-screen function has been added to the printer firmware, please update the firmware through the link below.
https://github.com/QIDITECH/QIDI_MAX3
https://github.com/QIDITECH/QIDI_PLUS3
https://github.com/QIDITECH/QIDI_SMART3

**Comment by r00tdownx** [comment]
Do you have a screenshot of how I can turn it on?

Thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by QIDITECH** [comment]
I'm very sorry that I couldn't reply you in time. In the future, we will arrange people to reply to the questions on github every day.

The current version only supports automatic screen off, and we will update it in the next version when the button is enabled. It will come soon.
