### ISSUE TITLE
Apple silicon dmg installation file

### ISSUE THREAD

**Issue by witchcraftsman** [QIDITECH/QIDISlicer#10]
Please add another release binary to support Apple ARM!
No problem to build it on Macbook (though you didn't publish required instructions from PrusaSlicer - https://github.com/prusa3d/PrusaSlicer/blob/master/doc/How%20to%20build%20-%20Mac%20OS.md),
but it's sort of time consuming.

**Comment by QIDITECH** [comment]
MacOS ARM is theoretically compatible with x86. What kind of problems have you encountered in the process of use? Please provide details of the problem and the configuration of your computer.

**Comment by witchcraftsman** [comment]
No problem, just keeping my apps optimized. Don't know if it's the case here though.
