### ISSUE TITLE
Device Tab Crashes Slicer in Linux 

### ISSUE THREAD

**Issue by nattymcfly5** [QIDITECH/QIDISlicer#103]
I am using Fedora 41. Originally, I had the issue of a blank device tab and login screen so it was advised to add WEBKIT_DISABLE_COMPOSITING_MODE=1 to my QIDISlicer desktop file which fixed the issue. However, when  I go to the Device tab and fluidd loads up the slicer immediately crashes.

I opened the slicer using terminal and see this error: 
Failed to create GBM buffer of size 2090x1268: Invalid argument
[1]    46884 segmentation fault (core dumped)  ./QIDISlicer_1.1.7_Linux.AppImage

**Comment by QIDITECH** [comment]
There are too many versions of Linux, which can lead to poor compatibility between different versions, and we will release multiple versions of linux in the next software update to address these compatibility issues.

**Comment by nattymcfly5** [comment]
As new customer your response is much appreciated, can't wait for the new version!
