### ISSUE TITLE
Qidi Slicer 1.1.7 is not listed in Win 10 Add/Remove programs list.

### ISSUE THREAD

**Issue by SteveQ1Pro** [QIDITECH/QIDISlicer#104]
Qidi Slicer 1.1.7 appeared to install correctly and functioned as intended. However, it is not listed in Windows 10 Add /Remove Programs list, to allow an Uninstall. It is also not listed the Program selection list. It can be found by typing "Qidi Slicer, but is listed as Qidi.stl. Also, there was no short cut Icon on my desktop.

**Comment by QIDITECH** [comment]
Thank you for your feedback, we will optimize the installation package in the next version.
You can find the uninstaller in the file installation directory.

**Comment by wjyLearn** [comment]
This issue was resolved in the latest version, so close this issue
