### ISSUE TITLE
QIDISlicer 1.2.1 issue

### ISSUE THREAD

**Issue by joeycoates** [QIDITECH/QIDISlicer#114]
Just updated to 1.2.1 and QIDISlicer is now bricked.

QIDISlicer GUI initialization failed

Error parsing QIDISlicer config file, it is probably corrupted. Try to manually delete the file to recover from the error. Your user profiles will not be affected.

C;\\Users\willi\AppData\Roaming\QIDISlicer\QIDISlicer.ini

The configuration file contains null characters.

**Comment by QIDITECH** [comment]
Sorry, we cannot reproduce the problem, please go to this path and send us the entire configuration folder.
C\Users\willi\AppData\Roaming\QIDISlicer\
Until we fix the problem, you can continue to use the software by deleting the configuration folder.

**Comment by AndrewC110675** [comment]
I am having the same problem today and the link it gives doesnt exist.

**Comment by AndrewC110675** [comment]
Where is the configuration folder because i for one cannot find it anywhere

**Comment by QIDITECH** [comment]
AppDate is usually a hidden folder. Please enter the path to jump directly or display the hidden folder.

**Comment by AndrewC110675** [comment]
I finally found it and deleted the file and all is working as it should.

**Comment by joeycoates** [comment]
How did you find the config folder?

**Comment by AndrewC110675** [comment]
Press the windows key plus R

**Comment by AndrewC110675** [comment]
It will popup with %AppData% at bottom left,then go to qidi slicer and find config file and delete it.

**Comment by AndrewC110675** [comment]
Let me know if you find it.

**Comment by joeycoates** [comment]
Yeah, that did it, thanks! I was just about to reload 1.17.1 or just use OrcaSlicer (which works fine as well).

**Comment by AndrewC110675** [comment]
Glad it worked out.
