### ISSUE TITLE
Different thumbnail formats used by Qidi printer but not able to set up in QIDISlicer

### ISSUE THREAD

**Issue by kiniad** [QIDITECH/QIDISlicer#16]
Unfortunately the Qidi printers uses the PNG thumbnail format in the fluidd web UI and a custom "QIDI" format (simage and gimage lines in gcode) on the printer screen.
In the current prusaslicer you could add e.g. "300x300/PNG, 300x300/JPG" in the printer settings "G-code thumbnails" to have 2 thumbnail formats in the gcode.
That's not possible in the QIDISlicer.
Please add this option to the QIDISlicer. 
(or even better change the format at the printer screen in future firmware updates)

**Comment by QIDITECH** [comment]
PNG format read speed is very slow, but we have found a solution to solve this problem, the next version we will be software and firmware thumbnail format unified to PNG format
