### ISSUE TITLE
Please allow other ports then 10088

### ISSUE THREAD

**Issue by Phil1988** [QIDITECH/QIDISlicer#18]
By default QidiSlicer sets the port to 10088.

If the 3D printer is on a different port, then it can connect to that printer.
![image](https://github.com/QIDITECH/QIDISlicer/assets/6054234/52c52ab5-a254-4cc7-a719-4ec32f7ca1eb)

Please allow to set a different port, so we can also use other printers with your slicer :)

**Comment by QIDITECH** [comment]
Connecting printers from other manufacturers will cause errors in the multi-device management function, which we will solve in the subsequent optimization. It may not be realized in the short term, please understand.

**Comment by PrintMan133** [comment]
+1

**Comment by whitekaren** [comment]
![image](https://github.com/QIDITECH/QIDISlicer/assets/130121731/23f9c77e-d6f7-472f-83cb-9910406b3a76)
In the software version 1.1.2, we added Klipper(via QIDI) option to host type. When you select this option, the software will automatically add port 10088 when connecting. The original Klipper(via Moonraker) option no longer automatically adds port 10088, so you can select Klipper(via Moonraker) in version 1.1.2, and then add other ports in the url to connect to devices from other manufacturers, looking forward to your further feedback

**Comment by Phil1988** [comment]
Great work! 
Thanks a lot! 👍

**Comment by Phil1988** [comment]
I get many user reports on this and tested it myself:

Its broken in QidiSlicer v1.2.1

![Image](https://github.com/user-attachments/assets/7b2cebaf-f9b3-497e-aa96-2aab0752ab19)

Works in QidiSlicer v1.1.6:

![Image](https://github.com/user-attachments/assets/dd38690e-ed42-4d75-b062-e683878b005f)

Could you please have a look at it and fix it again?
Thanks!

**Comment by Phil1988** [comment]
@QIDITECH Can you please have another look at this?
