### ISSUE TITLE
Navigating to "device" causes: "Unhandled unknown exception; terminating the application."

### ISSUE THREAD

**Issue by MaxDoss3** [QIDITECH/QIDISlicer#21]
On QidiSlicer-1.0.8 for Windows the following occurs.

When navigating QIDISlicer-1.0.8 in order to add a device this statement appears and will close the program:

"Unhandled unknown exception; terminating the application."

The current way I am working around it is by ignoring the window by clicking back onto the application, and continuing to add a machine to the list regardless. After a restart of the program all added devices are lost.

Printer used:
Qidi X-Plus 3
Firmware: 4.2.10

This is regardless of re-installation of the slicer application. 

Additionally after several attempts this feature no longer works regardless of (re)installation.

**Comment by QIDITECH** [comment]
Adding custom models can cause this issue to occur, we have fixed the issue and will release a new version in the near future. Until then, you can restore the custom model to normal by deleting it or deleting the profile.
