### ISSUE TITLE
Drag stl to platter from desktop, explorer, etc does not work

### ISSUE THREAD

**Issue by pmbroth** [QIDITECH/QIDISlicer#23]
When dragging stl file to platter, it does not  allow it.  Importing works though.  circle with slash is displayed. Worked on previous version.

**Comment by trancified** [comment]
Restart slicer?
________________________________
From: pmbroth ***@***.***>
Sent: Wednesday, January 10, 2024 8:33 AM
To: QIDITECH/QIDISlicer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [QIDITECH/QIDISlicer] Drag stl to platter from desktop, exploerer, etc doe nto work (Issue #23)


When dragging stl file to platter, it does not allow it. Importing works though. circle with slash is displayed. Worked on previous version.

**Comment by pmbroth** [comment]
LOL..   That worked….

**Comment by pmbroth** [comment]
if this issue occurs, I close and reopent the application.  This ocuured sveral times.

**Comment by QIDITECH** [comment]
Starting the software from the installation package will cause this problem to be sent, which should not be sent randomly during normal use. You can try running the software as an administrator.
