### ISSUE TITLE
image on display when stl sent to printer for printing is black

### ISSUE THREAD

**Issue by pmbroth** [QIDITECH/QIDISlicer#24]
Sending print jobs tp x-max 3, no image is diaplayed.  

it is set to Klipper  with  380x380/QIDI, 210x210/QIDI

**Comment by pmbroth** [comment]
I have tried with several stl's  all do the same thing.  Screen image is black.  I rolled back to 1.08 and no issues,.  Re-installed 1.1 and still the same - black box.

**Comment by QIDITECH** [comment]
Thank you very much for your testing and feedback, 1.1.0 has a lot of compatibility issues, we will continue to fix, and release again after completion.

**Comment by QIDITECH** [comment]
Thank you very much for your testing and feedback, 1.1.0 has a lot of compatibility issues, we will continue to fix, and release again after completion.

**Comment by pmbroth** [comment]
I removed the /qidi from the 380*380 seciton, and the thumbnail works wihtin the fluid display, but still does not show on the printer.

**Comment by QIDITECH** [comment]
A little mistake, we have re-uploaded 1.1.0, please re-download and install. In addition, there may be other bugs, if found, please timely feedback to us.

**Comment by pmbroth** [comment]
It Works!  Thank you Brian
