### ISSUE TITLE
Bug version 1.0.1

### ISSUE THREAD

**Issue by Cocodada83** [QIDITECH/QIDISlicer#26]
Following the update I no longer have the system presets available.
The image of the bed no longer looks like version 1.0.8

**Comment by QIDITECH** [comment]
Please try to update the configuration, if it still does not work, open the configuration folder, and after closing the software, delete the original configuration file, and then re-run the software.
Please provide your operating system and other more detailed information, such as your operating process, software screenshots, etc.
