### ISSUE TITLE
Spelling Errer  in Fans and Outputs 

### ISSUE THREAD

**Issue by pmbroth** [QIDITECH/QIDISlicer#27]
On Fans and Outputs

Motherboard Fan name is misspelled   

it is spelled as Borad - should be Motherboard Fan

![Screenshot 2024-01-13 171455](https://github.com/QIDITECH/QIDISlicer/assets/24501341/b29dbcaa-9d09-4da5-8c2f-f162e0d1663e)

**Comment by QIDITECH** [comment]
Ok, thank you for reminding me.
