### ISSUE TITLE
Label object doesn't work correctly

### ISSUE THREAD

**Issue by Lightning2X** [QIDITECH/QIDISlicer#3]
Label object always only produces a single object in GCODE output. The GCODE  file only includes the line `EXCLUDE_OBJECT_DEFINE NAME=stl_id_0_copy_0` Which creates an object around all the objects, instead of multiple objects.  Which results in fluidd only seeing one object instead of multiple

![image](https://github.com/QIDITECH/QIDISlicer/assets/32514161/b0411822-4a12-4113-bbcc-d444e1c6f03d)

**Comment by QIDITECH** [comment]
label objets now only supports octoprint, which is the original function of prusa, it does not support klipper's EXCLUDE_OBJECT. We will add this feature in subsequent updates, stay tuned.

**Comment by QIDITECH** [comment]
We have added the ‘Exclude Objects’ in version 1.0.6, please download the latest version of the software via the following link.
https://github.com/QIDITECH/QIDISlicer/releases/tag/V1.0.6
