### ISSUE TITLE
Device list always empty v1.1.0

### ISSUE THREAD

**Issue by potens1** [QIDITECH/QIDISlicer#30]
I'm using the Linux appimage

My printer is setup and configured, but it does not appears in the `Device` tab.
![image](https://github.com/QIDITECH/QIDISlicer/assets/3988571/41379bd7-2d1e-4cbe-a45c-731221bb46a9)

![image](https://github.com/QIDITECH/QIDISlicer/assets/3988571/78464b97-e5ec-48bc-a558-a45b31ace222)

Adding it manually in the `Device` tab, I can see the interface, but it is not saved and clicking another tab will loose it

![image](https://github.com/QIDITECH/QIDISlicer/assets/3988571/71ebd3d1-ead8-4b58-842c-0fd8fd12ed81)

![image](https://github.com/QIDITECH/QIDISlicer/assets/3988571/f6bd6de3-8d47-4d0a-920e-1284ca72c7b2)
The device is not present in the machine list

Clicking away and then on `Device` again brings me again to this screen
![image](https://github.com/QIDITECH/QIDISlicer/assets/3988571/f8b590cd-34d3-457c-b3ad-00ad9555b21a)

**Comment by derbasteller** [comment]
Gib mal folgendes in deinem Browser ein: **http://192.168.3.229:10088**
Und prüf mal ob sich jedes mal die IP ändert?
Wenn dein Gerät im Router auf DHCP steht könnte nach einem Neustart eine andere IP vergeben werden.
Und dann geht die Verbindung verloren!

**Comment by QIDITECH** [comment]
We can not reproduce your question, please tell me your Linux version and system architecture and other configurations.

**Comment by rt1970** [comment]
Same Problem.
Update: i have used new name and not used DNS-name of printer. Only IP.
Now it show my printer

**Comment by derbasteller** [comment]
DHCP ausgeschaltet? Feste IP? Direkt mit Kabel verbunden? WLAN ausgeschaltet?

**Comment by QIDITECH** [comment]
@rt1970 Can you describe in detail how you triggered this bug, preferably with pictures.
thank you.

**Comment by potens1** [comment]
> We can not reproduce your question, please tell me your Linux version and system architecture and other configurations.

I don't know if it was to me or to the German comment that I don't understand but here you are:

Arch Linux x64
Latest Qidi Slicer version (1.1.1) still has the issue.

I don't know what you need more picture I already put, in fact, it's what is already in your documentation.

**Comment by rt1970** [comment]
@potens1 
I´m german too. "derbasteller" means you should control the network like DHCP, WIFI etc...
But we have another problem
I work with Windows 10 Pro x64 and QIDI slicer 1.1.1

**Comment by QIDITECH** [comment]
rt1970 is right. But is your situation the same as his? In print_host, we added a judgment to exclude incorrect IP formatting, but we didn't take into account that you can also enter DNS-name, etc. Since the message pop-up in the photo you posted above just blocked the input box, I don't know if your question is consistent with rt1970. @potens1 
What are you inputing in Hostname, IP, URL?
![image](https://github.com/QIDITECH/QIDISlicer/assets/37525539/0dccdea0-acef-4e02-bd32-ee639ea5de50)

**Comment by potens1** [comment]
>  What are you inputing in Hostname, IP, URL? 
I'm using the hostname since the IP is assigned through DHCP and may, or may not get the same IP each time.
Using the IP (V4, and V4 only, ipv6 is not working either) does not show the bug, indeed. What is strange is, it works when using the hostname, until you switch tab

**Comment by QIDITECH** [comment]
Ok, thank you for your cooperation, we will fix the problem in the next version.

**Comment by whitekaren** [comment]
This problem has been solved in the 1.1.2 version of the software, you can download and use now, looking forward to your further feedback
