### ISSUE TITLE
Profiles for Qidi Printers

### ISSUE THREAD

**Issue by pganns** [QIDITECH/QIDISlicer#33]
Bambu Studio and Orca Slicer already have a profile for the Qidi XCF-Pro. I believe that there is no one more prepared to create other Qidi printer profiles within Qidi Slicer than Qidi itself. Obviously including i-fast.

**Comment by QIDITECH** [comment]
No older models will be added to QIDISlicer. If you need an older model, obtain the printer configuration through after-sales service and import it.
