### ISSUE TITLE
 No thumbnail with Qidislicer V1.1 on QIDI X-Smart

### ISSUE THREAD

**Issue by RS-3D** [QIDITECH/QIDISlicer#35]
Hello, since the update to V1.1 I can no longer see a thumbnail displayed on my Qidi-X-Smart 3. Can you help me with that?

**Comment by cl4nspi** [comment]
Please check the printer settings.

![qidi_xsmart3](https://github.com/QIDITECH/QIDISlicer/assets/47660640/74dea3f8-2dda-4502-b34a-597adcbd280e)

**Comment by RS-3D** [comment]
I checked it. I had the following (see picture). I copied the text from you and it works again. 
![image](https://github.com/QIDITECH/QIDISlicer/assets/124310197/efcf3c73-f1ff-4fe3-b5c3-a928e5dfc040)
Thanks
