### ISSUE TITLE
Timelaps and config-files: can not download

### ISSUE THREAD

**Issue by rt1970** [QIDITECH/QIDISlicer#37]
Hi!
I have Timelaps Plugin installed. I cant download Video.
Same in config-files.
No reaction if i click "download"
Please fix it!

**Comment by QIDITECH** [comment]
Try opening fluidd in your browser and downloading it

**Comment by rt1970** [comment]
Yes. That was my solution. But in older Version was no problem. Please fix it!

**Comment by QIDITECH** [comment]
Well, thank you for your feedback.
