### ISSUE TITLE
QIDI Slicer 1.1.1 Crash Mac Os Sonoma when star app, Mac Mini M1

### ISSUE THREAD

**Issue by JohnPetrucci** [QIDITECH/QIDISlicer#39]
<img width="1012" alt="Screenshot 2024-02-17 alle 19 56 37" src="https://github.com/QIDITECH/QIDISlicer/assets/22119735/08da2e20-7d74-4160-9a10-a681b940d340">

**Comment by QIDITECH** [comment]
It's missing a library. Install zstd and it will work.
If you are using Homebrew, just run:
brew install zstd
That should fix it.

We are working on a solution to this problem, so if you can't install zstd, please use v1.0.8 for now

**Comment by whitekaren** [comment]
In the latest 1.1.2 macOS arm64 version of the software has removed the dependency on the zstd library file, you can now download and use, looking forward to your further feedback
