### ISSUE TITLE
Infill bridging over supports.

### ISSUE THREAD

**Issue by r00tdownx** [QIDITECH/QIDISlicer#4]
Hi in new version of your slicer could you give us more options to control infill bridging over supports.
This is the only area I cannot get a clean surface, right where the print built off a support!
The bridge flow ratio doesn't do enough even at max 2, I get spaces between the print lines.
I'm on the Max3!
Thanks.
![image](https://github.com/QIDITECH/QIDISlicer/assets/142807917/9abcfaff-03cf-4b6b-bdb6-cb189ef690e2)

**Comment by QIDITECH** [comment]
Maybe you can try to close Thick bridges.
![image](https://github.com/QIDITECH/QIDISlicer/assets/37525539/9415f93f-b55d-4e0f-a716-2ae6ace457de)

**Comment by r00tdownx** [comment]
Hi I'm still getting bad bridging over supports with thick bridges on.  Solid infill is above bridge infill.
![Screenshot_1](https://github.com/QIDITECH/QIDISlicer/assets/142807917/f2d36dcf-d46a-4f18-bd4f-44e32341f421)
![Screenshot_2](https://github.com/QIDITECH/QIDISlicer/assets/142807917/d17b5e8a-0f14-405a-81d5-e29760e19834)
![Screenshot_3](https://github.

I've attached my bridge test.  Maybe you can try and show results?
[Bridge test.zip](https://github.com/QIDITECH/QIDISlicer/files/12736223/Bridge.test.zip)
com/QIDITECH/QIDISlicer/assets/142807917/90f5d8cb-acea-45a6-8c32-a274775a23b3)
