### ISSUE TITLE
QIDISlicer 1.1.1 pressure advance calibration issue

### ISSUE THREAD

**Issue by Vance1122** [QIDITECH/QIDISlicer#40]
When doing the pressure advance calibration, on both the lines and pattern option, the column of numbers is printer first and they are about 4mm tall. Then the tool head comes back to print the lines or pattern depending on which one you picked and the tool head runs into the numbers. In my case, the column of numbers stuck well enough for the tool head to move the build plate over on the platform. Please fix this. The number column could be 1mm tall from the surface or shorter and still be readable.

**Comment by QIDITECH** [comment]
Thanks for your feedback, we will fix the issue in the next release.

**Comment by QIDITECH** [comment]
Thanks for your feedback, we will fix the issue in the next release.

**Comment by whitekaren** [comment]
The 1.1.2 version of the software has fixed the problem you described, you can download it and use it now, looking forward to your further feedback
