### ISSUE TITLE
QIDI SLicer-1.1.1 Loss of part picture on X-plus 3

### ISSUE THREAD

**Issue by rayzor120** [QIDITECH/QIDISlicer#43]
Ever since the update, the part not showing in the display window. Old files before the update can still display part.

X-plus 3 running 
SOC: V4.2.13
MCU: V0.10.0
UI: V4.2.13

![XPlus 3 screen](https://github.com/QIDITECH/QIDISlicer/assets/159553705/d9a9f38d-39d8-48e6-9824-0175b441d148)

**Comment by cl4nspi** [comment]
https://github.com/QIDITECH/QIDISlicer/issues/35#issuecomment-1919652036

**Comment by rayzor120** [comment]
I agree.

**Comment by rayzor120** [comment]
Still trying to find the location in printer settings.

**Comment by cl4nspi** [comment]
> Still trying to find the location in printer settings.

Printer Settings -> general 
The setting is only visible in expert mode

**Comment by QIDITECH** [comment]
Update the slicing software configuration.
In order to better fit fluidd, the parameter format of the v1.1.1 preview has been changed. After the software is updated, the parameter configuration also needs to be updated for normal use.
