### ISSUE TITLE
Please add a "shrinkage" value for the filament types

### ISSUE THREAD

**Issue by Phil1988** [QIDITECH/QIDISlicer#44]
In SuperSlicer and OrcaSlicer you have a shrinkage option in the filament section.

This is important if you want accurate objects from materials that shrinks while cooling (like ABS/ASA, etc)
It would be nice to have this feature availible in QIDISlicer as well.

Here are examples of SuperSlicer at ABS:
![image](https://github.com/QIDITECH/QIDISlicer/assets/6054234/e045eef8-4350-41fc-a69c-d6640ce848f7)

Or from OrcaSlicer at ABS:
![image](https://github.com/QIDITECH/QIDISlicer/assets/6054234/bc63259a-4a8f-4c2e-8891-8d5360401911)

**Comment by QIDITECH** [comment]
Ok, we'll add and test this parameter.

**Comment by whitekaren** [comment]
You can now set the scale of the model according to the shrinkage rate of the filament in version 1.1.2 of the software for more accurate printing (thanks to OrcaSlicer), looking forward to your further feedback

**Comment by Phil1988** [comment]
@whitekaren You meant "thanks to SuperSlicer/supermerill" right?
Credits to the ones that have done it ;)

https://github.com/supermerill/SuperSlicer/issues/287
(Orcas parameter name is even the same as from SuperSlicer: "filament_shrink")
