### ISSUE TITLE
The printer wont start if the name of the file contains "é" characters

### ISSUE THREAD

**Issue by antoineseveau** [QIDITECH/QIDISlicer#49]
In QIDISlicer, if the name of the body contains a "é", very commun in french language, the printer wont start, the sending to the printer with wifi seems to works, but then nothing happens, no start print
![Capture d’écran 2024-03-06 à 18 41 47](https://github.com/QIDITECH/QIDISlicer/assets/146857863/ab2b3e2f-4bcc-4249-8ad9-33919f6e94ce)

**Comment by QIDITECH** [comment]
https://github.com/QIDITECH/QIDI_SMART3/issues/32
This is the same problem that belongs to the firmware, so turn it off here.
