### ISSUE TITLE
Change Filament Not Working X-Plus-3

### ISSUE THREAD

**Issue by embracemaking** [QIDITECH/QIDISlicer#5]
When using the insert change filament into gcode based on these instructions:

https://help.prusa3d.com/article/color-change_1687

it seems to get ignored by the printer and it doesn't pause allowing for filament change.

**Comment by QIDITECH** [comment]
Thank you for your feedback.
Change the color code ‘M600‘ is not recognized by the printer, you need to change it to ‘M0’.
![image](https://github.com/QIDITECH/QIDISlicer/assets/37525539/ade35241-ea7f-4811-abae-2cba888fc782)

We will update the configuration in the next release to fix this issue.
