### ISSUE TITLE
OS X Appearance not changing

### ISSUE THREAD

**Issue by wabbitguy** [QIDITECH/QIDISlicer#54]
Mac OX - Sonoma - X86
```
Version: 1.1.2
Build: QIDISlicer-1.1.2+Win64
Operating System: Macintosh
System Architecture: 64 bit
System Version: macOS Version 14.3.1 (Build 23D60)
Total RAM size [MB]: 17,180MB

OpenGL installation
GL version: 4.1.0
Profile: Core
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 5300 OpenGL Engine
GLSL version: 4.10.0
Textures compression: Enabled
```

Changing the OS X System Preferences - Light or Dark only affects the object/preview. All other settings are unaffected. Makes it very difficult to read some of the options text that appear in green (previous QIDI slicer displayed properly with "Dark" theme).

<img width="766" alt="*Untitled - QIDISlicer-1 1 2  2024-03-21 15-38-53" src="https://github.com/QIDITECH/QIDISlicer/assets/8953419/cbbb3498-7275-49d3-8a45-9e53f079c02a">

Extremely difficult to read:

<img width="461" alt="About QIDISlicer 2024-03-21 15-40-52" src="https://github.com/QIDITECH/QIDISlicer/assets/8953419/3a1f4d78-c9a6-45e7-86ec-240f16caa95e">

**Comment by majo1604** [comment]
Same issue here 😑

**Comment by QIDITECH** [comment]
We are very sorry, but in order to be compatible with the system version 10.13-11, we reduced the version of the SDK package and some dependencies, which caused this issue. We will solve this problem as soon as possible.

**Comment by QIDITECH** [comment]
We re-uploaded the installation package, please re-download and install the software.

**Comment by wabbitguy** [comment]
@QIDITECH downloaded and it's working perfectly. Thanks!
