### ISSUE TITLE
Can't install mac os arm version

### ISSUE THREAD

**Issue by witchcraftsman** [QIDITECH/QIDISlicer#56]
Hello, can't install version 1.1.2 for arm64 on mac os 12.7.4 (monterey), macbook with m1 pro, please see the screenshot.
<img width="372" alt="Screenshot 2024-03-30 at 11 44 50" src="https://github.com/QIDITECH/QIDISlicer/assets/60239912/e6a986b2-8b8d-4abb-8e44-6f7ac5fcc2e7">

**Comment by QIDITECH** [comment]
Please install the x86 version. The arm64 system is compatible with the x86 version software.
![1](https://github.com/QIDITECH/QIDISlicer/assets/37525539/90b2a641-b4b4-46a8-ad3e-bb4b829f30c6)

**Comment by witchcraftsman** [comment]
I used x86 before, but since you're targeting arm64 now, why not build it with previous OS versions support, not just current
