### ISSUE TITLE
QIDI Slicer 1.1.3 no MacOS_86 version

### ISSUE THREAD

**Issue by wabbitguy** [QIDITECH/QIDISlicer#57]
Can't install ARM slicer builds on an X86 based Mac.

**Comment by billkenney** [comment]
For some reason the x86 version was not included in the latest release. Not sure why, but I can't install it either.

**Comment by wabbitguy** [comment]
@billkenney they seems to be having some issues with the dark themes on the X86 version so they changed a bunch of libraries around (for the 1.1.2 version). I'm going to guess they are kind of hitting the same problems with the newer release.

**Comment by QIDITECH** [comment]
We have released the x86 version, please download the x86 version.
