### ISSUE TITLE
 infill/perimeter overlap does not work correctly for solid layers

### ISSUE THREAD

**Issue by hwilma** [QIDITECH/QIDISlicer#60]
Increasing the value for infill/perimeter overlap decreases the overlap for all top and bottom solid layers except the first and last one. The first and last solid layers and the infill layers are calculated correctly. 
This only applies when i use values in percent.

I am using QIDI Slicer 1.1.3 on Ubuntu.

**Comment by Gradbb** [comment]
Okay, the issue will be fixed in the next version.

**Comment by QIDITECH** [comment]
We have fixed this issue in the latest version.
