### ISSUE TITLE
PA calibration issue - Overlapping print

### ISSUE THREAD

**Issue by cptcl** [QIDITECH/QIDISlicer#63]
![Screenshot 2024-05-17 175904](https://github.com/QIDITECH/QIDISlicer/assets/53144288/fdb1c1c5-fc7c-40f6-b5cc-0325b40cee72)
Wanted to do a PA test for my PLA since i installed the bimetal hotend & nozzle...
It showed like this and also prints it like this. 
No matter what settings i use. from 0 to 0.04 or like in the screenshot.
Same issue

**Comment by QIDITECH** [comment]
Please close the Auto-center parts.
![image](https://github.com/QIDITECH/QIDISlicer/assets/37525539/a52d364e-d890-43f7-9ad3-9ba4232bd412)
