### ISSUE TITLE
Uninstall/Update behavior, does not automatically close older version of program to free up permissions to overwrite files.

### ISSUE THREAD

**Issue by raidenGitHub** [QIDITECH/QIDISlicer#64]
Qidislicer 1.1.4 install file does not automatically close Qidislicer 1.1.3 before installing.  
During install procedure, installer complains about libraries that are in use (because Qidislicer 1.1.3 is still open).
Uninstaller for Qidislicer 1.1.3 does not automatically close Qidislicer 1.1.3 before uninstalling. Program remains open, and uninstaller completes.

**Comment by QIDITECH** [comment]
Ok, we'll fix that. Thank you for your feedback.

**Comment by QIDITECH** [comment]
We have fixed this bug, please update the software to the latest version.
