### ISSUE TITLE
Can't access to the calibration tab

### ISSUE THREAD

**Issue by GXMV1978** [QIDITECH/QIDISlicer#66]
QidiSlicer V1.1.4 : I can see the "Calibration" tab but it's grey and not a link, i can't access any menu.

**Comment by GXMV1978** [comment]
![Capture d'écran 2024-06-03 124438](https://github.com/QIDITECH/QIDISlicer/assets/90828044/9295560e-1f8a-4aaf-b963-b07ad791865b)

**Comment by QIDITECH** [comment]
#67

**Comment by GXMV1978** [comment]
Thx
