### ISSUE TITLE
Qidislicer 1.1.4 menu item not showing / weird

### ISSUE THREAD

**Issue by GXMV1978** [QIDITECH/QIDISlicer#67]
Near the calibration tab that's non fonctionning for me (issue #66 ), there is an hidden tab that you can see at mouse over. If you click it, one set of brackets appear, if you click again, 2 sets of brackets, click again and 3 sets, and so on and so forth.
![mouser-over](https://github.com/QIDITECH/QIDISlicer/assets/90828044/84c42542-307e-4b82-841b-32420c27b7dd)

**Comment by QIDITECH** [comment]
Please close ‘Set settings tabs as menu items’.
The calibration does not yet support this setting.
![QQ截图20240604094902](https://github.com/QIDITECH/QIDISlicer/assets/37525539/b8455326-38cf-4bff-bca6-1b00be231f9f)

**Comment by GXMV1978** [comment]
Thanks a lot have a great day
