### ISSUE TITLE
Support for i-Fast printer

### ISSUE THREAD

**Issue by donnydavis** [QIDITECH/QIDISlicer#68]
We paid $2000 dollars for a printer that is being ignored.  We don't need all of the features, but at least a workable profile is a great start. 

Add support for the i-Fast.

**Comment by mtstarr** [comment]
Agreed, I now own $2000 brick....

**Comment by ivograca** [comment]
Agreed

**Comment by kvnper** [comment]
Yes please QIDI, this would be good

**Comment by runway37** [comment]
Sure would be great. Feels like the printer got less than three years before all resources were put towards the shiny new toys. That seems quite short sighted. Why buy one of the new gen of printers if support for a previous $2k printer lasts less than three years?  Maybe Qidi thinks there aren't enough ifasts out there to be worth the time it takes. But if so, that's short sighted.

**Comment by donnydavis** [comment]
Considering you still sell this printer, I don't see the issue in something as basic as a profile.

**Comment by pganns** [comment]
I reiterate my previous request that profiles for printers such as the i-fast and XCF Pro be included in Qidi Slicer. I remember that in Orca Slicer, there is already a profile for the XC Pro and that Qiditech is a sponsor of Orca Slicer. Therefore, I don't understand why it would be so difficult to create these profiles in Qidi Slicer.

Furthermore, some developers recently published in the Orca package the possibility of sending files via Wi-Fi to non-klipper printers, using esp3d (makerbase). Possibly, if QidiTech opens the code for the Control Panel in QidiPrint, the community will integrate communication between the I-Fast and XCF Pro printers.

**Comment by donnydavis** [comment]
I am working on this myself over here if anyone lands at this issue and nothing has been done about i-Fast support by Qidi. 

https://github.com/donnydavis/i-Fast

**Comment by pewt-pewt** [comment]
Either Qidi slicer support, or orca profile. Please. This machine is essentially a paper weight for so much cost…
