### ISSUE TITLE
RFE: Support for i-Fast printer

### ISSUE THREAD

**Issue by donnydavis** [QIDITECH/QIDISlicer#7]
I have both an i-Fast and X-Smart 3. This software looks great, but it's less than ideal to use two slicers. 

Please add support for older model printers, they weren't cheap and are great machines.

**Comment by QIDITECH** [comment]
We are trying to test and adjust the configuration of the printer, it may take some time to adapt to all models, you can contact our after-sales to get a simple version of the i-fast configuration file.
https://qidi3d.com/pages/warranty-policy-after-sales-support

**Comment by donnydavis** [comment]
A simple version isn't really what I am after. 

Don't we just have to convert this code to make it work?

https://github.com/QIDITECH/Qidi-Print/blob/main/python/qidi/Wifi/CBDConnect.py

**Comment by QIDITECH** [comment]
The assembly language used by the two software is different, and it is not a simple paste and copy, and the wifi function needs to be rewritten.
We need more time to solve these problems. Thank you for your support and understanding.

**Comment by donnydavis** [comment]
Understandable, however the functions and logic are the same. No pressure on time, that isn't what I am trying to say.

**Comment by QIDITECH** [comment]
Yes, all the code related to communication is in the following two links.
https://github.com/QIDITECH/Qidi-Print/tree/main/python/qidi/Wifi
https://github.com/QIDITECH/Qidi-Print/tree/main/plugins/ControlPanelPlugin
