### ISSUE TITLE
Qidi slicer crashes on windows 11 - running rtx 4080 nvidia

### ISSUE THREAD

**Issue by mohgarr** [QIDITECH/QIDISlicer#71]
Whenever I load a model and slice, it will crash after 20 - 30%

**Comment by mohgarr** [comment]
version 1.1.4 of qidislicer. I've got 96GB of RAM also.

**Comment by QIDITECH** [comment]
Will any model break down?
Have any parameters been modified? If so, please provide 3mf.

**Comment by mohgarr** [comment]
I've tried about 3 different models. None of them get past 30% before the
program crashes. And a couple of times it's blue screened windows.

**Comment by QIDITECH** [comment]
Can you provide the 3mf file of your model, we will try to repeat the problem.
And please try running the software in compatibility mode.

**Comment by QIDITECH** [comment]
No follow-up response, close the issue
