### ISSUE TITLE
Build on linux

### ISSUE THREAD

**Issue by C3362** [QIDITECH/QIDISlicer#74]
Hi
I have issue with running on Ubuntu 22.04 and wanted to build myself to avoid libraries conflicts. But do not see any instructions for that. 
Please add linux build instruction.
Thank you,

**Comment by QIDITECH** [comment]
https://github.com/prusa3d/PrusaSlicer/blob/master/doc/How%20to%20build%20-%20Linux%20et%20al.md
Please refer to prusa's build documentation.
