### ISSUE TITLE
Capricorn symbol incorrect slicing

### ISSUE THREAD

**Issue by C3362** [QIDITECH/QIDISlicer#75]
Hello
As odd it looks, somehow QIDI slicer 1.14 (Ubuntu) incorrectly slices Capricorn symbol
![Screenshot from 2024-06-23 08-52-43](https://github.com/QIDITECH/QIDISlicer/assets/150081699/2703bb4c-d0ff-456c-948b-6e7d99eede93)
After import it looks ok
![Screenshot from 2024-06-23 08-52-28](https://github.com/QIDITECH/QIDISlicer/assets/150081699/99d83691-3f67-4bdc-91ad-2d4e1f854f60)
slicing algo decides to invert internals
![Screenshot from 2024-06-23 08-52-13](https://github.com/QIDITECH/QIDISlicer/assets/150081699/9a6ac36f-c19d-4636-924d-e5227167a4c5)
[output (1).stl.zip](https://github.com/user-attachments/files/15945235/output.1.stl.zip)

Thank you

**Comment by QIDITECH** [comment]
There are some flaws in this model, which is not a software calculation error. We have fixed the model.
[output.zip](https://github.com/user-attachments/files/15948795/output.zip)

**Comment by C3362** [comment]
Thank you
