### ISSUE TITLE
Magikarp body repaired incorrectly

### ISSUE THREAD

**Issue by carol8** [QIDITECH/QIDISlicer#76]
Hi,

I tried to slice a broken STL and it repaired it wrongly, despite saying it repaired some edges:
![image](https://github.com/QIDITECH/QIDISlicer/assets/13537761/7ca9dfaf-6d83-4a12-95bf-cf40eca53d50)
![image](https://github.com/QIDITECH/QIDISlicer/assets/13537761/3773cedf-1e89-465d-8af9-9597ef27b4b2)

When loading this file in OrcaSlicer, repairing it there and slicing it using QIDISlicer I'm getting the correct result:
![image](https://github.com/QIDITECH/QIDISlicer/assets/13537761/70d148fc-2231-4a84-829b-fecc921bda12)
![image](https://github.com/QIDITECH/QIDISlicer/assets/13537761/13ea3c7e-73be-41c2-83a0-1b5cacca08f3)

The broken STL and the correct STL are available [here](https://drive.google.com/drive/folders/1QYCK-e3OROqIqV4NlY9NKu7OtprteO0-?usp=sharing)
If you have any questions about reproducing the error, ask and I'll respond ASAP. Thanks a lot!

**Comment by QIDITECH** [comment]
Can you provide this model to us? If you do not want to disclose this model, you can send it to our after-sales mailbox.

**Comment by carol8** [comment]
The model is available in the original message (see the underlined, blue link with the text "here" at the bottom of the message). If you are not able to click on the link, copy and paste it from here: [https://drive.google.com/drive/folders/1QYCK-e3OROqIqV4NlY9NKu7OtprteO0-?usp=sharing](https://drive.google.com/drive/folders/1QYCK-e3OROqIqV4NlY9NKu7OtprteO0-?usp=sharing)

**Comment by QIDITECH** [comment]
We were unable to reproduce the problem you said, the fix function on my computer can work properly and get correct results with Orca.

**Comment by QIDITECH** [comment]
Please try again to fix the model, and if that doesn't work, please record a video or screenshot to show me where the error occurred.

**Comment by carol8** [comment]
The fix function in Orcaslicer is working properly, but the fix function in QIDISlicer does not. I will record a video and send it to you later today. Thanks a lot!
