### ISSUE TITLE
appimage won't run, looking for shared library libwebkit2gtk-4.0.so.37

### ISSUE THREAD

**Issue by ChrisJones79** [QIDITECH/QIDISlicer#78]
This library didn't come with my standard Debian build 12.5 (Bookworm). What is the solution?

```
$ ./QIDISlicer_1.1.4_Linux.AppImage
/tmp/.mount_QIDISlVx7RSV/usr/bin/bin/qidi-slicer: 
 error while loading shared libraries: libwebkit2gtk-4.0.so.37: 
  cannot open shared object file: No such file or directory
```

**Comment by QIDITECH** [comment]
Yes, some linux systems don't come with libwebkit2gtk, so you'll need to install it manually.
sudo apt-get install libwebkit2gtk-4.0-dev

**Comment by ChrisJones79** [comment]
Ok, thanks. What if 4.0-dev is unavailable, is a newer version ok?

**Comment by kasunch** [comment]
Some of the latest distributions such as Ubuntu 24.04 upgraded the libwebkit2gtk to 4.1 and do not ship 4.0 any longer.  I solved the problem by extracting the appimage and creating a symbolic link as per the instructions in https://github.com/bambulab/BambuStudio/issues/3973#issuecomment-2097651206.

```bash
./QIDISlicer_<version>_Linux.AppImage --appimage-extract
ln -s /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0 squashfs-root/usr/bin/bin/libwebkit2gtk-4.0.so.37
ln -s /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so.0 squashfs-root/usr/bin/bin/libjavascriptcoregtk-4.0.so.18
``` 

You can run slicer using the following.
```bash
./squashfs-root/AppRun
```

**Comment by ChrisJones79** [comment]
Thanks a lot! I am not savvy on dealing with app images, I didn't know you
could fix them like that.
