### ISSUE TITLE
Slicer 1.1.5 will not permit dragging files onto the build plate

### ISSUE THREAD

**Issue by leckert123** [QIDITECH/QIDISlicer#80]
Just updated from 1.1.4.   1.1.5 will not allow me to drag stl files from a Win11 folder to the build plate. I have tried dragging the file from folders on Dropbox, my local drive, and desktop.  No success.  I don't see an option in preferences to address this. I did not have this issue with 1.1.4.

The only option is to use the File open or use the File icon (next to the trashcan icon) to open a file.  This slows down my work flow dramatically.

I will try to revert to 1.1.4 if possible until this is fixed.

**Comment by QIDITECH** [comment]
Please try running the software again.
This problem occurs when the software is directly run through the installation package due to insufficient permission.
