### ISSUE TITLE
Calibration Pressure Advance needs work.

### ISSUE THREAD

**Issue by ghyker** [QIDITECH/QIDISlicer#87]
The pressure advance test is wrong in the latest versions. The text is placed inside the lines and the nozzle crashes amongst the lines and text.
<img width="842" alt=" 2024-08-30 at 10 31 26 AM" src="https://github.com/user-attachments/assets/374dae45-fe34-4b7f-85dd-eb73e1dc7252">

**Comment by QIDITECH** [comment]
Please close the Auto-center parts.
![image](https://github.com/user-attachments/assets/62168885-159c-43f2-9ac6-47574419e8da)

**Comment by ghyker** [comment]
Your solution worked! Thank you.
