### ISSUE TITLE
No connected 3D Printer and no "send to printer" option

### ISSUE THREAD

**Issue by Anercomp** [QIDITECH/QIDISlicer#88]
After upgrading to 1.1.5 my printer is not automatically detected anymore. When opening the printer in "device" manually it shows up fine with all stats and camera feed and saying standby. Any help is appreciated, as there is no option displayed to send files to the printer . Thanks!
![image](https://github.com/user-attachments/assets/ec3c3959-696b-46ab-9f66-1cc830c0034c)

**Comment by QIDITECH** [comment]
Have you ever tried removing a device and adding it again?

**Comment by r00tdownx** [comment]
I have same problem!  I had to roll back to 1.15
![Screenshot_1](https://github.com/user-attachments/assets/90df1de7-2824-42cc-bc38-fbc459025895)
![Screenshot_2](https://github.com/user-attachments/assets/07855395-5ffe-4a20-a427-a021d099aca6)

**Comment by r00tdownx** [comment]
Error uploading to print host:
HTTP 500: {"error": {"code": 500, "message": "Internal Server Error", "traceback": "Traceback (most recent call last):\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 563, in move\n os.rename(src, real_dst)\n\nOSError: [Errno 18] Invalid cross-device link: '/tmp/moonraker.upload-464.mru' -> '/home/mks/gcode_files/Handle 008(20mm Screw).gcode'\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n File \"/home/mks/moonraker/moonraker/components/file_manager/file_manager.py\", line 673, in _process_uploaded_file\n upload_info['dest_path'])\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 577, in move\n copy_function(src, real_dst)\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 263, in copy2\n copyfile(src, dst, follow_symlinks=follow_symlinks)\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 122, in copyfile\n copyfileobj(fsrc, fdst)\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 82, in copyfileobj\n fdst.write(buf)\n\nOSError: [Errno 28] No space left on device\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n File \"/home/mks/moonraker/moonraker/app.py\", line 879, in post\n result = await self.file_manager.finalize_upload(form_args)\n\n File \"/home/mks/moonraker/moonraker/components/file_manager/file_manager.py\", line 532, in finalize_upload\n result = await self._finish_gcode_upload(upload_info)\n\n File \"/home/mks/moonraker/moonraker/components/file_manager/file_manager.py\", line 604, in _finish_gcode_upload\n finfo = await self._process_uploaded_file(upload_info)\n\n File

**Comment by r00tdownx** [comment]
Sorry my problem was printer was hard drive was full but was giving network time out error!

**Comment by QIDITECH** [comment]
As for the bug report, we have some problems with our judgment, which will be fixed in the next version.

**Comment by QIDITECH** [comment]
The issue should have been fixed in the new version, if it still exists, I will open the issue again.
