### ISSUE TITLE
0.6mm 0.8mm nozzles support

### ISSUE THREAD

**Issue by witchcraftsman** [QIDITECH/QIDISlicer#9]
Hi! This is enhancement request to support 0.6 and 0.8 mm nozzles with corresponding profiles (just like you made it for 0.2mm).
Just received your nozzles and willing to use them with X-Max 3 but don't have much time to fiddle with required configuration adjustment.

**Comment by QIDITECH** [comment]
An arbitrary configuration does not make for a good printing experience. 
We are testing and adjusting the parameters and will add 0.6 and 0.8 nozzles in the next version.

**Comment by witchcraftsman** [comment]
Good news!

**Comment by QIDITECH** [comment]
We have added 0.6 and 0.8 nozzle configurations, please update the software to the latest version.
https://github.com/QIDITECH/QIDISlicer/releases
