### ISSUE TITLE
"Send to Printer" dialog box unreadable

### ISSUE THREAD

**Issue by y-e-r** [QIDITECH/QIDISlicer#90]
QIDISlicer 1.1.6 AppImage, when system gtk theme is dark the "Send to printer" dialog box is unreadable. Dark text on dark background, and light text on light background. 
![Screenshot](https://github.com/user-attachments/assets/921acbc0-1721-42d3-94cd-f84458794861)

**Comment by QIDITECH** [comment]
OK, we will try to fix it in next version.

**Comment by wabbitguy** [comment]
@QIDITECH Mac_OSX86 has the same issue...

No idea what's supposed to be in those check boxes where the big white squares are. Be nice if you not only fixed it but explained what is "supposed" to be showing.

<img width="713" alt="Send G-Code to printer host 2024-09-26 11-43-32" src="https://github.com/user-attachments/assets/e75e6654-a789-4026-9ad6-7be461ad3977">

**Comment by QIDITECH** [comment]
In light mode, he is normal, only in dark mode will appear this way.
We will fix this issue in a future release.

**Comment by wabbitguy** [comment]
@QIDITECH thanks for the info. Least I know what the text is supposed to say now. Thanks.

**Comment by wabbitguy** [comment]
@QIDITECH update QIDI Slicer, now version 1.1.7 dark mode dialog box still not fixed.

**Comment by QIDITECH** [comment]
Yes, due to time constraints, we prioritized fixing some other issues, and this bug is still being fixed.

**Comment by jonXmack** [comment]
<img width="727" alt="image" src="https://github.com/user-attachments/assets/73b8b80d-00b5-434a-a273-10aefcf9c51b">

Thought I'd upload this so you can see what it actually says!

**Comment by QIDITECH** [comment]
We have fixed this issue in the latest version.
https://github.com/QIDITECH/QIDISlicer/releases
