### ISSUE TITLE
Open QIDI Slicer updates in my preferred browser - not the Chrome-in-slicer browser

### ISSUE THREAD

**Issue by leckert123** [QIDITECH/QIDISlicer#94]
I do not want to download updates from within the slicer.  It opens a mini-browser of the Git page from within the slicer and always downloads to my PC download folder.  

1.  That is not where I want to download the file
2. There are no options in the slicer to change the download folder, or to have it ask me where I want it to be downloaded.
3.  Changes to the default download folder for the PC, having it ask before downloading, and location for MS Edge have zero affect - and even if it did, I'd not want to change the location for ALL programs

What I want:
4.  Have the updates open a link to my default Firefox browser, which is courteous enough to ask where I want to download the file, AND it remembers my download preferences as well.

**Comment by QIDITECH** [comment]
You can select the download address in the Preferences.
![image](https://github.com/user-attachments/assets/060856a3-1a88-4e3f-82e9-2361e4ef3cab)

**Comment by leckert123** [comment]
That is selected as shown. Unfortunately the Slicer does not follow this setting and simply dumps it into the local downloads folder.

![image](https://github.com/user-attachments/assets/3bd74fe5-a076-4c39-957a-3747a04b0d77)

**Comment by QIDITECH** [comment]
I'm sorry I misunderstood you a little bit.
When you start the software and automatically check updates, the next button does not appear, so you can only download the installation package from the web. Manually check updates when the next button can be displayed normally, and select the download address.
We will fix this feature in a future release.

**Comment by QIDITECH** [comment]
We have fixed this issue in the latest version.
https://github.com/QIDITECH/QIDISlicer/releases
