### ISSUE TITLE
Seam gap seems to do nothing

### ISSUE THREAD

**Issue by KoeSource** [QIDITECH/QIDISlicer#97]
It looks as if the seam gap has no effect.
Whether I set 0% or 15% makes no difference in reality. A smaller gap is displayed in the slicer simulation.

Can anyone confirm this?

**Comment by QIDITECH** [comment]
0.4 * 15% = 0.06mm, which is almost invisible to the naked eye, maybe you can set it larger to observe the effect

**Comment by KoeSource** [comment]
How do i get those seam gaps ? Any idea?
something must be completely wrong...

outer diameter: 10mm
eSun PETG+HS, 0.8mm Nozzle, see zip for more info.

![2024-10-29 22_08_12-2024-10-29 22_05_24-IMG_20241029_220317062 1 jpg - IrfanView (Zoom_ 689 x 918)](https://github.com/user-attachments/assets/2cac3e1a-9a83-47c7-9e59-8f6bdad0edfe)
[qidi.zip](https://github.com/user-attachments/files/17563183/qidi.zip)

The only way I could correct it:
![grafik](https://github.com/user-attachments/assets/f21f0d69-bcf1-4a72-bbdd-d32232a3ff93)

**Comment by Gradbb** [comment]
I noticed that you have set the pullback distance to 1. Please set the pullback distance to 3mm or set it to the default value, which will effectively improve your seam.

**Comment by KoeSource** [comment]
> 1. Please set the pullback distance to 3mm or set it to the default value, which will effectively improve your seam.

1. It doesn't change anyhting about the seam gap
2. It creates an other issue -> blobs and ziz, the surface ist really ugly
If the retraction is over 1.5mm, i hear a small explosion inside the nozzle every retraction it does.

![grafik](https://github.com/user-attachments/assets/0a0e5718-0f63-4c75-9c74-fde783f87d4a)

![grafik](https://github.com/user-attachments/assets/f8dc3486-d176-43cf-b87c-5f206e7ff2f9)

**Comment by Gradbb** [comment]
> > 1. Please set the pullback distance to 3mm or set it to the default value, which will effectively improve your seam.
> 
> 1. It doesn't change anyhting about the seam gap
> 2. It creates an other issue -> blobs and ziz, the surface ist really ugly
>    If the retraction is over 1.5mm, i hear a small explosion inside the nozzle every retraction it does.
> 
> The following pictures are printed with same settings but retraction on default:
> 
> ![grafik](https://private-user-images.githubusercontent.com/4213418/381657759-0a0e5718-0f63-4c75-9c74-fde783f87d4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDIxMjgsIm5iZiI6MTczMDM0MTgyOCwicGF0aCI6Ii80MjEzNDE4LzM4MTY1Nzc1OS0wYTBlNTcxOC0wZjYzLTRjNzUtOWM3NC1mZGU3ODNmODdkNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDIzMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWNlNTYwOTdlZDNiZWZkOWQ4YTljNzYwMTEyMDVjMmYzNjQzODI4MGYyZDUyMGRhYjdlZGQ4MWNkMGI0YmMxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._ow_-imChs_ZbuvpbTNrWBadoqQxPpWxrrbsEXyBa58)
> 
> ![grafik](https://private-user-images.githubusercontent.com/4213418/381657895-f8dc3486-d176-43cf-b87c-5f206e7ff2f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDIxMjgsIm5iZiI6MTczMDM0MTgyOCwicGF0aCI6Ii80MjEzNDE4LzM4MTY1Nzg5NS1mOGRjMzQ4Ni1kMTc2LTQzY2YtYjg3Yy01ZjIwNmU3ZmYyZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDIzMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTAyMjIyMjA2MDdkZDBiYjFjNDc4OWJlYzQ5OTVmNTZjMzJiY2Y4ZjZhM2VjYjkyMmQ2MzFhYWJhNDU5YTJjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3A-kKbGjgDxLIFBd80KOe-lqtrdNF6N5zRlRa0JDDto)

![f2](https://github.com/user-attachments/assets/f57d6b54-a69e-40b5-b252-92ecfe9c9e3d)

I have tested your file again, and you can also improve your seams by modifying the 'Deretraction extra length'. This is the effect I have achieved, and my value is 0.4mm. This value should not be set too high as it may cause excessive surface extrusion.
![FIGURE](https://github.com/user-attachments/assets/fea7e787-5673-4aa0-9dad-0bae608351da)

**Comment by KoeSource** [comment]
This leads to over-extrusion at the end.
It only leads to a slight improvement in the seam gap.
I only want to reduce or overlap the gap.
Is there no better solution?

![image](https://github.com/user-attachments/assets/b5bd5ab0-2acc-483b-8e91-1e3a24d6c6b9)

**Comment by Gradbb** [comment]
Hello, this is my printed result.
![1](https://github.com/user-attachments/assets/61dd57ab-cb66-4179-afc5-cea1daf7752f)
I made the following adjustments on your 3mf.
![2](https://github.com/user-attachments/assets/f02ef2d2-cffc-41bf-ac9c-167902ec1843)
![3](https://github.com/user-attachments/assets/c3f65c97-bda5-448c-9607-733899d9917d)
![4](https://github.com/user-attachments/assets/0f3ac2f0-dcc4-4455-bc54-96b017b1f2cb)
In addition, for nozzles with a diameter of 0.8mm, this situation is usually caused by overflow. You can also try lowering the printing temperature to improve this situation.

**Comment by KoeSource** [comment]
Thank you very much for your help.
This is pretty good for me.
I printed those standoffs with your settings at 230°C:

![grafik](https://github.com/user-attachments/assets/953c5ba5-690c-473e-ae6c-5bd29cf3a50b)
