### ISSUE TITLE
Variable Temperature & Flow Control

### ISSUE THREAD

**Issue by QidiBoi** [QIDITECH/QIDISlicer#99]
Hello QidiTech - 

I was wondering/hoping that your team may already be working on incorporating variable temperature & flow control g-codes into QidiStudio - see links below.   Please advise.   

Variable Temperature 3D Printing – The FUTURE of 3D Printing?
https://www.youtube.com/watch?v=P6Y8uUPd3yg&ab_channel=PRINTINGPERSPECTIVE   

SB53 G-Code Flow/Temperature Controller V1.1
https://github.com/sb53systems/G-Code-Flow-Temperature-Controller/releases/tag/V1.1

**Comment by Gradbb** [comment]
Hello, currently there is no such feature. If your requirement is to make the outer wall shine the same, you can enable "Don't slow down outer walls".
![f](https://github.com/user-attachments/assets/4a332c35-2bed-4443-9c24-ea44c18603d4)

**Comment by QidiBoi** [comment]
I'm not finding the variable you mentioned above - where is this located?  I'm using qidistudio 1.9.7.53

**Comment by Gradbb** [comment]
![f3](https://github.com/user-attachments/assets/2474b31a-a940-487b-9946-66c19cc724f8)
It is located on the filaments settings page.
If you have any questions about QIDI Studio, you can ask them on the [page.](https://github.com/QIDITECH/QIDIStudio/issues)
